/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MemeCoin = IDL.Record({
  'decimals' : IDL.Nat8,
  'name' : IDL.Text,
  'symbol' : IDL.Text,
  'contractAddress' : IDL.Text,
});

export const idlService = IDL.Service({
  'getMemeCoin' : IDL.Func([], [MemeCoin], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MemeCoin = IDL.Record({
    'decimals' : IDL.Nat8,
    'name' : IDL.Text,
    'symbol' : IDL.Text,
    'contractAddress' : IDL.Text,
  });
  
  return IDL.Service({ 'getMemeCoin' : IDL.Func([], [MemeCoin], ['query']) });
};

export const init = ({ IDL }) => { return []; };